### ISSUE TITLE
GUI editor mangling the measure_time in some cases

### ISSUE THREAD

**Issue by portoren** [newrelic/nr1-pathpoint#51]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

When a time window other than the Time-Picker default is selected, for example, "60 minutes ago", all touchpoints that did not have measure_time are temporarily calculated from the Time-Picker selection (SINCE 1668428490 UNTIL 1668428790). This change becomes permanent if the Touchpoints GUI editor is opened and the “Save Update” button is clicked.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

1. To verify the Touchpoints GUI editor before making changes in the Time-Picker.

![image](https://user-images.githubusercontent.com/2637031/202556143-b439eb47-4aa2-496f-971c-4365a4ac1176.png)

2. Change the selection in the Time-Picker to 30 minutes:

![image](https://user-images.githubusercontent.com/2637031/202556342-4fa97aa6-fbca-42b0-8f58-f9ce8a576511.png)

3. The touchpoint graphic editor opens and clicks on the “Save Update” button.
 
4. The Pathpoint is reloaded with the Time-Picker in its default selection and the graphical editor of touchpoints is opened. It is evident that all the touchpoints that did not have a custom measure_time have been modified:

![image](https://user-images.githubusercontent.com/2637031/202556467-6cca6801-98dd-42d5-b198-3558e16d5ce1.png)

5. Likewise, the touchpoints that have the custom measure_time are not affected by the action of the GUI editor:

![image](https://user-images.githubusercontent.com/2637031/202556526-b902343b-4b58-4646-9b23-44919bf9b6a8.png)

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

Touchpoints GUI editor should not save changes in measure_time with Time-Picker effects.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used: @datanerd/nr1/2.83.5 win32-x64 node-v16.11.1
* Browser name and version: Firefox 107.0 (64 bit)
* Operating System and version: Windows 10
* Pathpoint version: 1.7.3

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by JimHagan** [comment]
Thanks for the submission @portoren I saw this issue occur in a customer account.  Glad you are able to track it down.

Here is how we are going to handle this...

1. We want to NEVER save an absolute time window (one with a SINCE *AND* an UNTIL clause) -- We should raise an error if that is attempted.

2. We will consider renaming the five minutes ago entry in the time picker to simply say "NOW".  This will mean that the time picker will always be setting the `point in time`.  Then the `measurement_time` will be a `lookback` form the point in time.  

3. NOTE let's consider raising an error if the user tries to load a JSON file with a touchpoint using an `UNTIL` clause.  We should disallow it.

FYI @Sandeep10parmar

**Comment by JimHagan** [comment]
Please also add the "version found in" in the report.

**Comment by JimHagan** [comment]
@portoren Any more estimate on how long it may take to work on this?
